hash-format = "sha256"

[[files]]
file = "README.txt"

[[files]]
file = "assets/even_more_tfc/textures/item/metal/triple_ingot/bismuth.png"

[[files]]
file = "assets/even_more_tfc/textures/item/metal/triple_ingot/bismuth_bronze.png"

[[files]]
file = "assets/even_more_tfc/textures/item/metal/triple_ingot/black_bronze.png"

[[files]]
file = "assets/even_more_tfc/textures/item/metal/triple_ingot/black_steel.png"

[[files]]
file = "assets/even_more_tfc/textures/item/metal/triple_ingot/blue_steel.png"

[[files]]
file = "assets/even_more_tfc/textures/item/metal/triple_ingot/bronze.png"

[[files]]
file = "assets/even_more_tfc/textures/item/metal/triple_ingot/copper.png"

[[files]]
file = "assets/even_more_tfc/textures/item/metal/triple_ingot/red_steel.png"

[[files]]
file = "assets/even_more_tfc/textures/item/metal/triple_ingot/steel.png"

[[files]]
file = "assets/even_more_tfc/textures/item/metal/triple_ingot/wrought_iron.png"

[[files]]
file = "client_scripts/jsconfig.json"

[[files]]
file = "config/client.json"

[[files]]
file = "config/common.json"

[[files]]
file = "config/probe-settings.json"

[[files]]
file = "config/tfc.json"

[[files]]
file = "config/web_server.json"

[[files]]
file = "package.json"

[[files]]
file = "server_scripts/anvil.js"

[[files]]
file = "server_scripts/armorer.js"

[[files]]
file = "server_scripts/jsconfig.json"

[[files]]
file = "server_scripts/new_tags.js"

[[files]]
file = "server_scripts/smith_recipe.js"

[[files]]
file = "server_scripts/smith_recipe_lock.js"

[[files]]
file = "server_scripts/test.js"

[[files]]
file = "server_scripts/triple_ingot_properties.js"

[[files]]
file = "startup_scripts/jsconfig.json"

[[files]]
file = "startup_scripts/triple_ingot.js"
