name = "Minecraft Modpack . Terr Firma Factions"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb4d0d38eefad56d90f03e9651dd750c8fb658d4b6d2d88d0ee2a9bd92e396a6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
