name = "TerraFirmaFactions"
author = "binaryclock03"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82ce01b721224ef93d4b2a60cd886dd6eb3509a5f6a5ac53a62bdf293bc0621f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
