[electric_fridge]
	#Maximum FE/RF stored by one electric fridge. Minimum 5 FE/RF.
	# Default: 1000
	# Range: > 5
	energyCapacity = 1000
	#FE/RF consumed every server tick. Default 5/tick
	# Default: 5
	# Range: > 0
	energyConsumptionPerTick = 5
	#TFC decay modifier applied to foods inside while unpowered. Set to 1.0 disable unpowered benefits.
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	unpoweredSpoilageRate = 0.5
	#TFC decay modifier applied to foods inside while powered. Set to 1.0 to disable powered benefits and GUI elements. If set to 1.0, powered fridge will use unpowered modifier if it isnt also 0.
	# Default: 0.25
	# Range: 0.0 ~ 1.0
	poweredSpoilageRate = 0.25
	#Number of 9-slot rows in the electric fridge inventory.
	# Default: 2
	# Range: 1 ~ 6
	fridgeRows = 2
	#Maximum TFC item size allowed in fridge slots. Items larger than this cannot be inserted.
	#Allowed Values: TINY, VERY_SMALL, SMALL, NORMAL, LARGE, VERY_LARGE, HUGE
	maxItemSize = "NORMAL"
	#If true, hoppers, pipes, and other item-transfer automation can insert into and extract from the electric fridge.
	enableItemAutomation = false
